### ISSUE TITLE
"bbl up" to AWS AZ "us-west-2d" fails due to lack of "t2.medium" instance type

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/bosh-bootloader#444]
Hi BBL Team,

We (Diego Persistence) just started to see failures to `bbl up` in the `us-west-2` AWS region:
```
+ eval bbl --debug up --name heleus --lb-type=cf --lb-cert=/tmp/bbl-cert --lb-key=/tmp/bbl-key --lb-domain=heleus.persi.cf-app.com '2>&1' '>' /tmp/build/4431eb96/bbl_up.log
++ bbl --debug up --name heleus --lb-type=cf --lb-cert=/tmp/bbl-cert --lb-key=/tmp/bbl-key --lb-domain=heleus.persi.cf-app.com

Error: Error applying plan:

1 error(s) occurred:

* aws_instance.nat: 1 error(s) occurred:

* aws_instance.nat: Error launching source instance: Unsupported: Your requested instance type (t2.medium) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2c, us-west-2b, us-west-2a.
	status code: 400, request id: ae9d2bc6-e72c-4834-bce4-62a8f7aaeb6e

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Executor apply: exit status 1
```
The annoying thing is that `bbl destory` then fails ...
```
# bbl --debug destroy
Are you sure you want to delete infrastructure for "heleus"? This operation cannot be undone! (y/N): y
step: cleaning up director resources


Read jumpbox vars file: open /tmp/build/4431eb96/bbl-state/bbl-state-aws-heleus/vars/jumpbox-vars-store.yml: no such file or directory
```
... so you have to manually clean up by navigating to the `terraform` sub-directory and running `terraform destroy -state=../vars/terraform.tfstate -var-file=../vars/bbl.tfvars`. Once everything is cleaned up, we can re-run the `bbl-up` CI job, which succeeds, presumably because it chooses a different AZ.

Does the `t2.medium` instance type for the NAT instance need to be updated to something that is more globally available, or is there a way to exclude `us-west-2d` from the list of AZs?

Regards,
Dave

**Comment by Polar-Beard** [comment]
Hi @davewalter, we just pushed a change to fix this issue. We switched the nat instance to use a `t3.medium`, which is the newer version of a `t2.medium`, and is available on the az. 

https://github.com/cloudfoundry/bosh-bootloader/commit/08ed356bad251ed52a493522e8588b716b96fa4a

**Comment by zachgersh** [comment]
This has now been fixed by this release: https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v7.3.0

**Comment by vroad** [comment]
The same issue still occurs whenever running EC2 instance fails.
In my case my accout reached instance count limit. Max instance count of t3.medium is set to 1, so I guess you need to open a case to raise the limit every time you create new account on AWS. Can a real fix be implemented, so that you don't need to destroy infrastructure manually when initialization fails?
